language: csharp
solution: "./WebDemoAzureCD/WebDemoAzureCD.sln"
install:
  - nuget restore ./WebDemoAzureCD/WebDemoAzureCD.sln
script:
  - xbuild /p:Configuration=Release ./WebDemoAzureCD/WebDemoAzureCD.sln
  - mono ./WebDemoAzureCD/packages/xunit.runners.console.*/tools/net452/xunit.console.exe ./WebDemoAzureCD/WebDemoAzureCD.Tests/bin/Release/WebDemoAzureCD.Tests.dll
