language: csharp
solution: WebDemoAzureCD.sln
install:
  - nuget restore WebDemoAzureCD.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release WebDemoAzureCD.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./WebDemoAzureCD.Tests/bin/Release/WebDemoAzureCD.Tests.dll