language: csharp
solution: "./WebDemoAzureCD/WebDemoAzureCD.sln"
script:
  - xbuild /p:Configuration=Release WebDemoAzureCD.sln
  - mono ./WebDemoAzureCD/packages/xunit.runners.*/tools/xunit.console.clr4.exe ./WebDemoAzureCD/WebDemoAzureCD.Tests/bin/Release/WebDemoAzureCD.Tests.dll
