language: csharp
solution: "./WebDemoAzureCD/WebDemoAzureCD.sln"
install:
  - travis_retry nuget restore -source "https://www.nuget.org/api/v2" ./WebDemoAzureCD/WebDemoAzureCD.sln
script:
  - xbuild ./WebDemoAzureCD/WebDemoAzureCD.sln
  - mono ./WebDemoAzureCD/packages/xunit.runner.console*/tools/xunit.console.exe ./WebDemoAzureCD/WebDemoAzureCD.Tests/bin/Debug/WebDemoAzureCD.Tests.dll
